const express = require("express");
const router = express.Router();
const authController = require("../../controllers/auth/authController");
const sessionAuth = require("../../middleware/sessionAuth");
router.post("/send-otp", authController.sendOtp);
router.post("/verify-otp", authController.verifyOtp);
router.post("/resend-otp",authController.resendOtp);
router.post("/register", authController.register);
router.post("/login", authController.login);
router.post("/set-pin",authController.setPin);
router.get("/user-profile", sessionAuth, authController.getUserProfile);
router.post("/verify-login-otp",authController.verifyLoginOtp);
router.post("/resend-login-otp",authController.resendLoginOtp);
module.exports = router;
