apiVersion: apps/v1
kind: Deployment

metadata:
  name: payo-backend
  namespace: payo-prod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payo-backend

  template:
    metadata:
      labels:
        app: payo-backend

    spec:
      containers:
        - name: payo-backend
          image: 011237054417.dkr.ecr.ap-south-1.amazonaws.com/payo-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3001

          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "3001"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: DB_PASSWORD

            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: DB_SERVER

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: DB_DATABASE

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: DB_PORT

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payo-backend-secret
                  key: JWT_SECRET

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"